# arm_cartesian_compliance_controller:
#   type: "velocity_controllers/CartesianComplianceController"
#   end_effector_link: "$(arg tf_prefix)ee_link_ur5"    # All links below must come before this link
#   robot_base_link: "$(arg tf_prefix)base_link_ur5"
#   ft_sensor_ref_link: "$(arg tf_prefix)wrist_3_link_ur5"
#   compliance_ref_link: "$(arg tf_prefix)tool_link_ur5"
#   target_frame_topic: "target_frame" #target_frame
#   joints:
#     - $(arg tf_prefix)shoulder_pan_joint
#     - $(arg tf_prefix)shoulder_lift_joint
#     - $(arg tf_prefix)elbow_joint
#     - $(arg tf_prefix)wrist_1_joint
#     - $(arg tf_prefix)wrist_2_joint
#     - $(arg tf_prefix)wrist_3_joint

#   stiffness:  # w.r.t. compliance_ref_link
#       trans_x: 500
#       trans_y: 500
#       trans_z: 500
#       rot_x: 100
#       rot_y: 100
#       rot_z: 100

#   pd_gains:
#       trans_x: {p: 0.05}
#       trans_y: {p: 0.05}
#       trans_z: {p: 0.05}
#       rot_x: {p: 0.01}
#       rot_y: {p: 0.01}
#       rot_z: {p: 0.01}

arm_cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "$(arg tf_prefix)ee_link"    # All links below must come before this link
    robot_base_link: "$(arg tf_prefix)base_link"
    ft_sensor_ref_link: "$(arg tf_prefix)wrist_3_link"
    compliance_ref_link: "$(arg tf_prefix)tool_link"
    target_frame_topic: "target_frame" #target_frame
    joints:
      - $(arg tf_prefix)shoulder_pan_joint
      - $(arg tf_prefix)shoulder_lift_joint
      - $(arg tf_prefix)elbow_joint
      - $(arg tf_prefix)wrist_1_joint
      - $(arg tf_prefix)wrist_2_joint
      - $(arg tf_prefix)wrist_3_joint

    stiffness:
        trans_x: 800
        trans_y: 800
        trans_z: 800
        rot_x: 100
        rot_y: 100
        rot_z: 100

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 0.01}
        rot_y: {p: 0.01}
        rot_z: {p: 0.01}


#arm_velocity_controller: #input: one joint position
#  type: velocity_controllers/JointPositionController
#  joints:
#   - $(arg tf_prefix)shoulder_pan_joint
#    - $(arg tf_prefix)shoulder_lift_joint
#    - $(arg tf_prefix)elbow_joint
#    - $(arg tf_prefix)wrist_1_joint
#    - $(arg tf_prefix)wrist_2_joint
#    - $(arg tf_prefix)wrist_3_joint
#  pid_gains: {p: 100.0, i: 0.01, d: 10.0}
