initial_pose:
  joint_names: ["elbow_joint",
                "shoulder_lift_joint",
                "shoulder_pan_joint",
                "wrist_1_joint",
                "wrist_2_joint",
                "wrist_3_joint"]
  joint_values: [-0.0020376876207999217, 
                 -1.5813632074074961, 
                 0.00877147645387133, 
                 -1.5706180138634331, 
                 -1.563270237637747, 
                 -0.0005246588949265885]
